---
- include_vars:         "../../../sensitive_ansible/roles/{{ role_name }}/vars/main.yml"
- include:              '../tasks/create_files.yml'
- include:              '../tasks/template_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/lines_in_files.yml'
- include:              '../tasks/restart_services.yml'
  when:                 create_files_result.changed
                        or install_files_result.changed
                        or lines_in_files_result.changed
