---
- include_vars:         "sensitive/vars/main.yml"
- include_tasks:        'tasks/common/install_packages.yml'
- include_tasks:        'tasks/common/lines_in_files.yml'
- include_tasks:        'tasks/common/create_files.yml'
- include_tasks:        'tasks/common/shell_commands_ignore_change.yml'
- include_tasks:        'tasks/common/template_files.yml'
- include_tasks:        'tasks/common/install_files.yml'
- include_tasks:        'tasks/common/symlinks.yml'
- include_tasks:        'tasks/common/restart_services.yml'
  when:                 create_files_result.changed
                        or install_files_result.changed
                        or lines_in_files_result.changed
